dataset_name: ego4d
devices: cuda
train_split: ['training']
val_split: ['validation']
dataset: {
  save_dir: cached_datasets,
  task: all_fb,
  max_txt_len: 384,
  nar_rand_window_expansion_factor: 5.0,
  nlq_rand_window_expansion_factor: 1.0,
  mnaq_dist_params: [0.68468357165,599.0975553520426,-1.755742557530719e-27,20.332493617659544,0.13333000000000084,480.0],
  debug: False,
  training_task_types: ["narr", "nlq", "goalstep_nlq", "hd_epic_nlq", "nlq_feedback", "goalstep_nlq_feedback", "hd_epic_nlq_feedback"],
  mnaq_random_order: False,
  naq_ratio: 1,
  num_workers: 2,
  video_feat_dir: features/offline_lmdb/decord_egovideo_video_features,
  text_feat_dir: features/offline_lmdb/new_gte_qwen2_role,
  vid_feat_dir: features/decord_egovideo_vid,
  search_domain_dir: features/offline_lmdb/search_domain,
  nlq_gt: annotations/nlq_val_annotated.json,
  nlq_feedback_gt: nlq_feedback_val.json,
  moment_gt: annotations/moments_val.json,
  goalstep_gt: annotations/processed_goalstep_val_sorted.json,
  goalstep_nlq_gt: annotations/sampled_goalstep_val_with_nlq.json,
  goalstep_nlq_feedback_gt: gs_feedback_val.json,
  hd_epic_nlq_gt: annotations/sampled_hd_epic_val_with_nlq.json,
  hd_epic_nlq_feedback_gt: hd_epic_feedback_val.json,
  narr_gt: narr_val.json,
  qcaa_narr_gt: dataset/feedback/narr_val.json,
  qcaa_goalstep_gt: dataset/feedback/goalstep_val.json,
  num_classes: 1,
  input_vid_dim: 512,
  input_txt_dim: 3584,
  feat_stride: 16,
  num_frames: 16,
  default_fps: 30,
  max_seq_len: 2304,
  summary_len: -1,
  relative_pe_resolution: 1000,
  negative_sample: 0,
  negative_sampling_tasks: ["narr", "goalstep"],
  hard_negative_sample: 0.,
  cluster_ratio: 1.,
  crop_video: 0.,
  anchor_prob: 0.5,
  modifier_prob: 0.5,
  moment_neg_sampling: 0.05,
  sampling_type: narration_centric,
  anchor_search_seconds: 120,
  curriculum: null,
  mini_batch_sampling: "random",
  val_pass: 1,
  train_pass: 1,
  sample_single_gt: [],
  keep_original: [],
  merge_overlapping_span: False,
  val_clip_overlap: 0.25,
  use_conditional_trj: False,
  sample_reference_task: "nlq",
  sample_feedback_ratio: -1,
  use_pooled_token: False,
  use_role_token: False,
  filter_guidelines: [],
  val_feedback_narr: [],
  use_gt_feedback: [],
  use_separate_feedback: ["nlq_feedback", "goalstep_nlq_feedback", "hd_epic_nlq_feedback"],
  use_temporal_feedback: [],
  gen_train_temp_feedback: 0.2,
  randomize_tfb_timestamps: True,
  goalstep_filter_duration_threshold: 9999999,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 2.0,
  n_mha_win_size: -1,
  backbone_type: "flashTransformer",
  backbone_arch: [1, 2, 2, 4, 6],
  # shrink the model for reduced input feature channels
  n_head: 8,
  embd_dim: 512,
  fpn_dim: 512,
  head_dim: 384,
  use_abs_pe: True,
  regression_range: [[0, 4], [2, 8], [4, 16], [8, 32], [16, 64], [32, 128],[64, 10000]],
  narr_decoder: False,
  num_summarizer_blocks: 1,
  summary_resolution: 10000,
  summary_of_summary: False,
  head_num_layers: 3,
  single_token_language: False,
  anchor_localization: False,
  consecutive_masking: False,
  provide_visual_info: False,
  predict_visual_info: True,
  contrastive_learning: False,
  localization_refinement: False,
  video_mask_ratio: 0.,
  fb_drop_nlq_ratio: 0.,
  train_feedback_only: False,
  falm_scale: 4,
  localization_loss_weight: 1.0,
  use_falm: True,
  falm_resume_path: null,  # set to FALM checkpoint path to load separately, or leave null to load from main checkpoint
}
falm_model: {
  arch: [1, 2, 2, 2, 1],
  input_vid_dim: 512,
  input_txt_dim: 3584,
  max_seq_len: 2304,
  n_head: 8,
  n_mha_win_size: -1,
  embd_dim: 512,
  embd_with_ln: True,
  train_cfg: {
    dropout: 0.1,
    attn_dropout: 0.,
    droppath: 0.1,
  },
  saliency_loss_weight: 1,
  scores_loss_weight: 1,
  multi_level_saliency_span: False,
}
opt: {
  learning_rate: 0.000001,
  epochs: 50,
  warmup_epochs: 1,
  weight_decay: 0.05,
  backbone_lr_weight: 1,
}
loader: {
  batch_size: 16,
  num_workers: 8
}
train_cfg: {
  init_loss_norm: 200,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
  droppath: 0.1,
  dropout: 0.1,
  attn_dropout: 0.,
  loss_weight: 1.0,
  negative_loss_weight: 1
}
test_cfg: {
  voting_thresh: 0.9,
  pre_nms_topk: 500,
  # max of 50 predictions per video
  max_seg_num: 50,
  min_score: 0.001,
  nms_sigma : 0.75,
  duration_thresh: 0.001,
}
narr_decoder_cfg: {
  num_layers: 2,
  n_head: 4,
  dropout: 0.1,
  droppath: 0.1,
  n_mha_win_size: -1,
  use_rel_pe: False,
  narr_loss_weight: 0.5,
}
anchor_localization_cfg: {
  num_layers: 3,
  dropout: 0.1,
  anchor_localization_weight: 1,
}
consecutive_masking_cfg: {
  consecutive_mask_range: [4, 20],
  droprate: 0.2,
}
contrastive_learning_cfg: {
  contrastive_loss_weight: 0.25,
  background_ratio: 0.25,
  temperature: 0.1
}
provide_visual_info_cfg: {
  context_action_order: 0,
  add_language: False,
  reduction: "mean",
}
predict_visual_info_cfg: {
  layers: 4,
  embd_dim: 384,
  n_head: 4,
  freeze_qcaa: True,
  lang_prob: 0.5,
  context_action_order: -1,
  context_order_multiplier: 1,
  add_language: True,
  reduction: "mean",
  use_pos: True,
  loss_type: ["vis", "lang"],
  vis_info_loss_weight: 1,
  temperature: 0.1,
  l2_loss: False,
  l2_loss_weight: 1,
  iterative_anticipation: 1,
  anticipate_low_to_high: False,
  across_batch: False,
  across_pred: True,
  use_duplicate_mask: False,
  order_loss: False,
  order_loss_weight: 2, 
  order_distance: 3,
  lang_info_loss_weight: 1,
  order_num_layers: 2,
  uniform_vid_sample: 100,
  query_dropout: 0,
  resume_path: /uufs/chpc.utah.edu/common/home/alhalah-group1/users/nikesh/Ego4d_NLQ_baseline/QCAALang_nlq/results/ckpt_qcaa_ego4d/QCAALang_66960.t7
}
localization_refinement_cfg: {
  num_layers: 2,
  dropout: 0.1,
  localization_refinement_weight: 1,
  direction_sample_radius: 2.5,
  dim: 16,
}
output_folder: results